name: Build and Publish Docker Image

on:
  push:
    branches: [main]
    tags: ['*']

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push image
        env:
          LABEL: ${{ github.ref_type == 'tag' && github.ref_name || 'main' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.LABEL }}
          labels: version=${{ env.LABEL }}
