name: Build Docker Image

on:
  push:
    branches: [main]
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        env:
          LABEL: ${{ github.ref_type == 'tag' && github.ref_name || 'main' }}
        run: |
          docker buildx build --platform linux/arm64 \
            --label version=$LABEL \
            -t dns-updater:$LABEL \
            --load .
